name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        extensions: mbstring, xml, ctype, iconv, intl, pdo, dom, filter, gd, json
        tools: composer:v2
    
    - name: Install dependencies
      run: composer install --prefer-dist --no-progress --no-interaction --optimize-autoloader
    
    - name: Create required directories
      run: |
        mkdir -p private/data/qr-generated
        mkdir -p private/data/qr-uploads
        mkdir -p logs
        mkdir -p cache
        chmod -R 755 private/data
    
    - name: Create environment file
      run: cp .env.example .env
    
    - name: Build Docker image
      run: docker build -t portfolio .
