name: CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        php-versions: ['7.4', '8.0', '8.1', '8.2']
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php-versions }}
        extensions: mbstring, xml, ctype, iconv, intl, pdo, pdo_mysql, dom, filter, gd, json
        coverage: xdebug
    
    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v3
      with:
        path: vendor        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-
    
    - name: Install dependencies
      run: |
        composer install --prefer-dist --no-progress --no-interaction
        composer dump-autoload
    
    - name: Create required directories
      run: |
        mkdir -p private/data/qr-generated
        mkdir -p private/data/qr-uploads
        mkdir -p logs
        mkdir -p cache
        chmod -R 755 private/data
        touch private/data/qr-generated/.gitkeep
        touch private/data/qr-uploads/.gitkeep
    
    - name: Create test environment file
      run: |
        cp .env.example .env || echo "DEBUG_MODE=true" > .env
    
    - name: Run code style check
      run: composer cs-check || echo "Code style check failed, continuing..."
      - name: Run static analysis
      run: composer phpstan || echo "Static analysis failed, continuing..."
    
    - name: Run tests
      run: composer test
    
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./clover.xml
        flags: unittests
        name: codecov-umbrella
        fail_ci_if_error: false

  security:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'
        extensions: mbstring, xml, ctype, iconv, intl, pdo, pdo_mysql, dom, filter, gd, json
    
    - name: Install dependencies
      run: composer install --prefer-dist --no-progress
    
    - name: Run security audit
      run: composer audit

  build-docker:
    runs-on: ubuntu-latest
    needs: [test, security]
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    
    - name: Build Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        platforms: linux/amd64,linux/arm64
        push: false
        tags: portfolio-web-tools:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max
